### ISSUE TITLE
Deploy lambda code via S3

### ISSUE THREAD

**Issue by jgeluk** [RJPearson94/terraform-aws-open-next#10]
## Is your feature request related to a problem

The problem is the incredibly long time that it takes to update the lambda functions of this module.
Usually more than half an hour. Perhaps due to the fact that they're deployed with access to a VPC but on the other hand, other lambda functions, not in this module but in the same project, with the same access to the VPC, take less than 30 seconds to update.

## Describe the solution you'd like

The culprit could be the size of the code for functions like `server_function`.
Perhaps it helps to first upload the code to a separate code bucket and refer to those files straight from the lambda config. This may then also help avoid an update if the eTag of those files is the same.

**Comment by RJPearson94** [comment]
Hi @jgeluk,

Work to add S3 support is currently in progress, along with a number of other changes/ improvements. There is no ETA for these changes yet. Depending on timelines & testing, I will try to get this out independently.

When looking at the opennext documentation, you can minify your server function; the documentation can be found at https://github.com/sst/open-next/blob/5acd30d91892ac25991e72f5243657637be9d5f1/docs/pages/advanced/options.mdx#L39-L57
This may help to reduce the bundle size in the interim

The performance of other lambda updates is interesting. I have a couple of questions:
- Do these other lambdas use lambda urls?
- Have you tried deploying these lambda functions outside of the VPC to see if the update time improves?

Kind Regards
Rob

**Comment by jgeluk** [comment]
Hi @RJPearson94, the "other lambda functions" that I mentioned at the top of this thread do not use lambda urls no. They get triggered by SNS events actually. Is that what makes it so slow, those lambda URLs?

The strange thing is that while terraform is still running, giving messages like this:
```
module.open-next.module.server_function["root"].aws_lambda_function.lambda_function: Still modifying... [id=xxx-server-function, 55m0s elapsed]
╷
│ Error: publishing Lambda Function (xxx-server-function) version: waiting for completion: exceeded max wait time for FunctionUpdated waiter
│
│   with module.open-next.module.server_function["root"].aws_lambda_function.lambda_function,
│   on .terraform/modules/open-next/modules/tf-aws-lambda/main.tf line 3, in resource "aws_lambda_function" "lambda_function":
│    3: resource "aws_lambda_function" "lambda_function" {
│
╵
╷
│ Error: publishing Lambda Function (xxx-revalidation-function) version: waiting for completion: exceeded max wait time for FunctionUpdated waiter
│
│   with module.open-next.module.revalidation_function["root"].aws_lambda_function.lambda_function,
│   on .terraform/modules/open-next/modules/tf-aws-lambda/main.tf line 3, in resource "aws_lambda_function" "lambda_function":
│    3: resource "aws_lambda_function" "lambda_function" {
│
╵
```

About the `--minify` option, it resulted in decreasing the size of the code (for the server function) from 14.3MB to 13MB so not shocking, the deploy via terraform still hangs (while the lambda function is updated if you look at in the console)

**Comment by jgeluk** [comment]
I found the problem that caused the "hang" with every terraform deploy, running terraform in debug mode showed the error, missing `lambda:GetFunctionConfiguration` policy... Now it deploys in 10 seconds (even without the minify option and with `OPEN_NEXT_DEBUG=true`) :-)
