### ISSUE TITLE
`invalidate-cloudfront.sh` script contains CR/LF pairs causing issues

### ISSUE THREAD

**Issue by jgeluk** [RJPearson94/terraform-aws-open-next#12]
## Technical Details

- OS: Linux
- Module Version 2.0.0
- Module Affected legacy

## Describe the bug

Invalidation ID in the script ends up with a \r in the value causing script to fail.

`INVALIDATION_ID=<some-value>\r`

## Additional context

Fixed with `dos2unix` utility, problem solved.

**Comment by jgeluk** [comment]
![image](https://github.com/RJPearson94/terraform-aws-open-next/assets/864726/9294ed18-186b-4b93-a8d7-268ffd1bb94c)

**Comment by RJPearson94** [comment]
Hi @jgeluk,

Apologies about this, and thanks for the detailed summary. This issue should have been resolved.

Please use v2.0.1 of the module which includes the fix.

Kind Regards
Rob

**Comment by jgeluk** [comment]
No worries, thanks, this can happen to the best :-)

**Comment by jgeluk** [comment]
Hi, for some reason the issue returned with version 2.0.2. Running `dos2unix` over the file reduces it from 550 to 539 bytes.

**Comment by jgeluk** [comment]
Hi Rob, I ran a terraform deploy again, after an init, which pulled the latest version, and got this error again:

<img width="930" alt="image" src="https://github.com/RJPearson94/terraform-aws-open-next/assets/864726/db95f118-9e3d-4627-a9a9-350d951cc089">

**Comment by RJPearson94** [comment]
hi @jgeluk, looking into this. That file shouldn't have been changed

**Comment by RJPearson94** [comment]
looking at the git history, that file has been touched since [v2.0.1](https://github.com/RJPearson94/terraform-aws-open-next/releases/tag/v2.0.1) was released. So not sure what is going on there

**Comment by RJPearson94** [comment]
Are you able to share any non-sensitive data from doing a `git config --list`
I'm interested in what your autocrlf setting value is, as I wonder if the file is being changed when terraform/terragrunt is cloning from GitHub. 
More info on the setting can be found at https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings?platform=linux
