### ISSUE TITLE
Error during `terragrunt plan`

### ISSUE THREAD

**Issue by Saba-Shavidze** [RJPearson94/terraform-aws-open-next#19]
@RJPearson94

I update the version = 2.2.1, but getting some unknown error, could you help me to elaborate?

```ts
+ bucket_arn             = (known after apply)
  + bucket_name            = (known after apply)
  + custom_error_responses = []
  + zone_config            = {
      + bucket_domain_name             = (known after apply)
      + bucket_origin_path             = (known after apply)
      + image_optimisation_domain_name = (known after apply)
      + reinvalidation_hash            = (known after apply)
      + server_at_edge                 = false
      + server_domain_name             = (known after apply)
      + server_function_arn            = (known after apply)
      + use_auth_lambda                = false
    }
ERRO[0021] tofu invocation failed in /Users/user/Projects/terraform-aws-open-next-examples/single-zone/.terragrunt-cache/kEInx4vf7Phm3eLvhbcvBHvQrYg/WZq5uaBnondhezazcPLKTiwZRgY/modules/tf-aws-open-next-zone  prefix=[/Users/user/Projects/terraform-aws-open-next-examples/single-zone] 
ERRO[0021] 1 error occurred:
        * [/Users/user/Projects/terraform-aws-open-next-examples/single-zone/.terragrunt-cache/kEInx4vf7Phm3eLvhbcvBHvQrYg/WZq5uaBnondhezazcPLKTiwZRgY/modules/tf-aws-open-next-zone] exit status 1
```

**Comment by RJPearson94** [comment]
Hi @Saba-Shavidze,

That is quite an obscure error. Are you able to share any more of the output? 
As you have gone from v2.0.x to v2.2.1, I suspect the lockfile hasn't been updated correctly. So you may need to run `terragrunt init -upgrade`

I have just pushed an update to the single zone example to use the updated package.json and the latest version of the module. Using this config and after the artefacts have been built, I have been able to deploy this using both Terraform (v1.6.5) and OpenTofu (v1.6.0).

Can you try the `terragrunt init -upgrade` and re-apply the changes?
If that fails to work, can you try the changes I have just pushed to the example and see if the issue re-occurs?
If that still fails, can you include more of the error log (please mask secrets or AWS account info) and the version of Terragrunt and OpenTofu you are using?

I can try to assist further.

Kind Regards
Rob

**Comment by Saba-Shavidze** [comment]
@RJPearson94  Thanks for your time and feedback, finally it works with

```ts
open-next: 2.3.5
provider-version: 2.2.1

```

**Comment by RJPearson94** [comment]
Glad I could help @Saba-Shavidze
