### ISSUE TITLE
`server_function` missing environment variables CACHE_BUCKET_NAME and CACHE_BUCKET_REGION

### ISSUE THREAD

**Issue by ValorMorgan** [RJPearson94/terraform-aws-open-next#2]
## Technical Details

- OS: Windows 11
- Terraform Version: 1.5.2
- Provider Version: aws (latest)
- Module Version: 1.0.3
- Next.js Version: 13.4.5
- OpenNext Version: 2.0.1

## Describe the bug

After successfully deploying all resources, visiting the CloudFront URL produced a 500 error.  CloudWatch logs revealed that the AWS S3 operation to fetch cached rendering from the S3 bucket failed because the bucket name was not specified.  Digging into the terraform module code revealed that the following environment variables are not set thus the `server_function` fails.
* CACHE_BUCKET_NAME
* CACHE_BUCKET_REGION

Information on these variables can be found at https://github.com/serverless-stack/open-next#server-lambda-function

## Steps to Reproduce

Steps to reproduce the behaviour:

1. Deploy following instructions in README
2. Visit the CloudFront URL

## Expected behaviour

Visiting the CloudFront URL renders the app/site as expected.

## Logs

> START RequestId: b4b98239-9bcc-4d6b-b4af-7a40edac8688 Version: $LATEST
> 
> 2023-06-28T15:20:25.407Z	b4b98239-9bcc-4d6b-b4af-7a40edac8688	ERROR	{
      clientName: 'S3Client',
      commandName: 'ListObjectsV2Command',
      input: { Bucket: undefined, Prefix: 'nH7tv5SZmJTCRKzlEAQuP/favicon.ico' },
      error: Error: No value provided for input HTTP label: Bucket.
          at U4 (/var/task/cache.cjs:20:9782)
          at Woe (/var/task/cache.cjs:31:100000)
          at async /var/task/cache.cjs:2:382,
      metadata: undefined
    }
> 
> 2023-06-28T15:20:25.408Z	b4b98239-9bcc-4d6b-b4af-7a40edac8688	ERROR	Error: No value provided for input HTTP label: Bucket.
        at U4 (/var/task/cache.cjs:20:9782)
        at Woe (/var/task/cache.cjs:31:100000)
        at async /var/task/cache.cjs:2:382
> 
> END RequestId: b4b98239-9bcc-4d6b-b4af-7a40edac8688

## Additional context

This was easily fixed manually by visiting the `server_function` and adding these missing environment variables.  The S3 bucket used was the `website_bucket`.

**Comment by RJPearson94** [comment]
Hi @ValorMorgan,

Sorry you have encountered this issue, I am currently working on support for open next 2.x.x. Currently the module is only compatible with 1.x.x

Support for open next 2.x.x should be out in the next version of the module.

**Comment by RJPearson94** [comment]
Hi @ValorMorgan,

Support for Open Next 2.x has been added and pushed to the Terraform Registry. Please upgrade to using at least v1.1.0 of the module to be able to utilise this functionality.

```tf
module "open-next" {
  source  = "RJPearson94/open-next/aws"
  version = "1.1.0"
}

```

I'm going to close the issue. Please feel free to open another issue for any additional feature requests/ issues.

Thanks for using the module

Kind Regards
RJPearson94
