### ISSUE TITLE
After Deployment getting 500 errors on some static routes

### ISSUE THREAD

**Issue by Saba-Shavidze** [RJPearson94/terraform-aws-open-next#20]
I deployed the application with `terraform-aws-open-next` with multi-zone approach:

```ts
module "deploy" {
  source = "./terraform-aws-open-next/modules/tf-aws-open-next-multi-zone"
  prefix = "iac"
  deployment = "SHARED_DISTRIBUTION_AND_BUCKET"

  zones = [
    {
      root        = true
      name        = "web-application"
      folder_path = "../.open-next"
    }
  ]

  website_bucket = {
    force_destroy = var.s3_force_destroy
  }

  providers = {
    aws.global          = aws.global
    aws.iam             = aws.iam
    aws.dns             = aws.dns
    aws.server_function = aws.server_function
  }
}

```

After succesfully deployment, some statically generated content fetch getting 500 error:

```ts
Request URL:
https://x1234.cloudfront.net/ka/%E1%83%A1%E1%83%A3%E1%83%9E%E1%83%94%E1%83%A0-%E1%83%9B%E1%83%A8%E1%83%9D%E1%83%91%E1%83%94%E1%83%9A%E1%83%98-1/%E1%83%9B%E1%83%A8%E1%83%9D%E1%83%91%E1%83%9A%E1%83%98%E1%83%A1-%E1%83%9B%E1%83%A8%E1%83%9D%E1%83%91%E1%83%94%E1%83%9A%E1%83%98-1/%E1%83%9B%E1%83%A8%E1%83%9D%E1%83%91%E1%83%94%E1%83%9A%E1%83%98-%E1%83%99%E1%83%90%E1%83%A2%E1%83%94%E1%83%92%E1%83%9D%E1%83%A0%E1%83%98%E1%83%90-1/%E1%83%A1%E1%83%90%E1%83%91-%E1%83%99%E1%83%90%E1%83%A2%E1%83%94%E1%83%92%E1%83%9D%E1%83%A0%E1%83%98%E1%83%90-2/%E1%83%A1%E1%83%90%E1%83%91-%E1%83%A1%E1%83%90%E1%83%91-%E1%83%99%E1%83%90%E1%83%A2%E1%83%94%E1%83%92%E1%83%9D%E1%83%A0%E1%83%98%E1%83%90/%E1%83%A1%E1%83%90%E1%83%91-%E1%83%A1%E1%83%90%E1%83%91-%E1%83%9E%E1%83%A0%E1%83%9D%E1%83%93%E1%83%A3%E1%83%A5%E1%83%A2%E1%83%98?_rsc=6gs74
Request Method: GET
Status Code: 500 Internal Server Error
Referrer Policy: strict-origin-when-cross-origin

```

and maybe I don't exactly know but, getting 500 errors while trying to access nextauth api request:

```ts
https://x1234.cloudfront.net/api/auth/providers
Request Method:GET
Status Code:500 Internal Server Error
```

**Comment by RJPearson94** [comment]
Hi @Saba-Shavidze,

Are you able to share any logs from the lambda function (api route) or the cloudfront distribution? As I’m not quite sure why this is causing a 500 status code to be returned.

Are you also able to share the next js and open next version you are using?

**Comment by shavidze** [comment]
`nextjs: 14`
`open-next: 2.3.6`

There is no logs enabled in cloudfront distribution and in server-function labmda I don't see any logs while trying to sign up with socials, to see some logs while getting 500 from nextauth api request.

**Comment by shavidze** [comment]
ops, sorry, I can see this kind of errors while trying to sign up using `nextuath`:

```ts
{
  clientName: 'DynamoDBClient',
  commandName: 'BatchWriteItemCommand',
  input: { RequestItems: { 'iac-web-application-isr-tag-mapping': [Array] } },
  error: AccessDeniedException: User: arn:aws:sts::***:assumed-role/iac-web-application-server-function-role/iac-web-application-server-function is not authorized to perform: dynamodb:BatchWriteItem on resource: arn:aws:dynamodb:eu-central-1:***:table/iac-web-application-isr-tag-mapping because no identity-based policy allows the dynamodb:BatchWriteItem action
      at throwDefaultError (/var/task/cache.cjs:10:5073)
      at /var/task/cache.cjs:10:5239
      at de_CommandError (/var/task/cache.cjs:41:65230)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /var/task/cache.cjs:2:55466
      at async file:///var/task/index.mjs:11:1230
      at async file:///var/task/index.mjs:10:15749
      at async file:///var/task/index.mjs:2:20315
      at async Promise.all (index 0)
      at async Eh.batchWriteDynamoItem (/var/task/cache.cjs:60:62043) {
    '$fault': 'client',
    '$metadata': {
      httpStatusCode: 400,
      requestId: 'XXX',
      extendedRequestId: undefined,
      cfId: undefined,
      attempts: 1,
      totalRetryDelay: 0
    },
    __type: 'com.amazon.coral.service#AccessDeniedException'
  },
  metadata: {
    httpStatusCode: 400,
    requestId: 'XXX',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```

**Comment by RJPearson94** [comment]
Hey @Saba-Shavidze, which environment variable is this?
You can supply additional environment variables through env variables for the server function

**Comment by RJPearson94** [comment]
Looking at that error, it looks like it is failing to write to the ISR mapping table. There might be permissions missing for ISR. Need to look at this further

**Comment by Saba-Shavidze** [comment]
Yes, it's not the problem I will update the policy.
Yep I noticed it later to pass additional environment variables to server function.
Thanks a lot for your quick reply every time I ask you something you're always trying to help me, really appreciate it.

**Comment by RJPearson94** [comment]
I have just pushed out a new module version; this should resolve the permissions problem with DynamoDB. There were a few missing permissions on SQS, too.
I have updated it to be in line with what is in the CDK construct/ ion implementation

Can you use v2.2.2 of the module to see if this resolves your issue?

**Comment by RJPearson94** [comment]
I'm happy to help.
Thanks for using the module and providing feedback/ raising any issues

**Comment by Saba-Shavidze** [comment]
One more question, Why the open-next alias versions does not update? next is updating but open-next does not

**Comment by RJPearson94** [comment]
So the aliases are there to help with continuous deployment, do you have this enabled?
If you have continuous deployment enabled, the module will update the alias which is associated with the staging env I.e. next and then when the change is promoted the aliases flip I.e. open-next will update
If continuous deployment is disabled, the alias associated with the primary distribution is updated, the staging alias doesn’t need to update as it’s not used.

I have been meaning to write up a blog post about how that works but not had the time recently.
Hope that helps

**Comment by shavidze** [comment]
How to enable it? I changed them manually to always point to $LATEST.
Can't really understand for now, but it's okay.

I'm working with cognito and have some problems, maybe u would give me some advices,
When the user authenticate via SOCIAL provider, in this case with google, everything works fine I'm creating the user with cognito, but when I'm trying to update the phone number it throws the 500 ERROR, on locally it works fine.

I pass the additional policy to the server-function:

__data.tf__
```ts
data "aws_caller_identity" "current" {}

data "aws_iam_policy_document" "cognito_policy" {
  statement {
    actions = [
      "cognito-idp:AdminCreateUser",
      "cognito-idp:AdminDeleteUser",
      "cognito-idp:AdminGetUser",
      "cognito-idp:AdminUpdateUserAttributes",
      "cognito-idp:UpdateUserAttributes",
      "cognito-idp:AdminSetUserPassword",
      "cognito-idp:AdminConfirmSignUp",
      "cognito-idp:InitiateAuth",
      "cognito-idp:SignUp"
    ]
    resources = [
      "arn:aws:cognito-idp:${var.cognito_region}:${data.aws_caller_identity.current.account_id}:userpool/${var.cognito_user_pool_id}"
    ]
  }
}
```

__main.tf__

```ts
  server_function = {
    additional_environment_variables = {
      "NEXTAUTH_URL"         = var.nextauth_url
      "NEXTAUTH_SECRET"      = var.nextauth_secret
      "COGNITO_DOMAIN"       = var.cognito_domain
      "COGNITO_REGION"       = var.cognito_region
      "COGNITO_USER_POOL_ID" = var.cognito_user_pool_id
      "COGNITO_ISSUER"       = var.cognito_issuer
      "AUTH_COGNITO_ID"      = var.auth_cognito_id
      "AUTH_COGNITO_SECRET"  = var.auth_cognito_secret
    },
    additional_iam_policies = [
      {
        name   = "cognito_policy",
        policy = data.aws_iam_policy_document.cognito_policy.json      }
    ]
  }
```

In cloudwatch logs I have this kind of error :

`UnrecognizedClientException: The security token included in the request is invalid.`

**Comment by RJPearson94** [comment]
Hi @shavidze,

There is a [readme](https://github.com/RJPearson94/terraform-aws-open-next/blob/main/docs/continuous-deployments.md) for continuous deployment which explains the config, etc.

On the Cognito error, have you built a custom UI for login & user details management?
if so are you able to share the sdk call you use on the server to modify the phone number?

**Comment by shavidze** [comment]
Thanks, I already fixed it.
Anyway thanks.

**Comment by RJPearson94** [comment]
Hey @shavidze, are you able to share more about what the fix was?
Curious if I can do anything to improve the documentation or make any more examples.

**Comment by shavidze** [comment]
https://gist.github.com/cmawhorter/3cf67164414c4a97fcd8#beware-env-credentials
