### ISSUE TITLE
Failed to update prerender cache

### ISSUE THREAD

**Issue by jgeluk** [RJPearson94/terraform-aws-open-next#27]
## Technical Details

- OS: Linux server-side, in the server-function lambda
- Terraform Version: 1.8.0
- Provider Version: aws 5.43.0 - 5.45.0
- Module Version: 2.3.0
- Module Affected tf-aws-open-next-zone
- Deployment Model: Single zone

## Describe the bug

Seen in the CloudWatch log group for the server function:

```
2024-04-16T11:31:29.110Z	d1c63d24-e4ab-4bc1-bf05-a8ad1d721558	WARN	Failed to update prerender cache for /index [Error: EROFS: read-only file system, open '/var/task/.next/server/app/index.html'] {
  errno: -30,
  code: 'EROFS',
  syscall: 'open',
  path: '/var/task/.next/server/app/index.html'
}
```

## Steps to Reproduce

Always happens

## Expected behaviour

Should not happen :-)

**Comment by RJPearson94** [comment]
hi @jgeluk,

That's a strange one. It looks like it's trying to read the files from the lambda filesystem rather than s3, etc.
Which version of open-next are you using?

**Comment by RJPearson94** [comment]
Looking on the open-next discord, this might be an issue where next.js changed something that broke open next. So, you need to bump the open-next version.

I saw it mentioned next.js 14.1 require open-next@2.3.5
message: https://discord.com/channels/983865673656705025/1205501166625234955/1205506842763989012

Hope this helps

**Comment by RJPearson94** [comment]
Hi @jgeluk, 

Have you managed to try updating the open next dependency version to see if this resolves your issue?
As this looks like an open next issue rather than an issue with the module itself

Kind Regards
Rob

**Comment by RJPearson94** [comment]
Hey @jgeluk, Have you managed to try the steps above?

**Comment by RJPearson94** [comment]
closing issue, as this appears to be an open next compatibility issue
