### ISSUE TITLE
Image Optimisation Function not working

### ISSUE THREAD

**Issue by adatoo** [RJPearson94/terraform-aws-open-next#31]
## Technical Details

- OS: MacOS
- Terraform Version: 1.7.4
- AWS Provider Version 5.51.1
- Module Version: 3.0.0

## Describe the bug

Image optimisation not working.

## Steps to Reproduce

Steps to reproduce the behaviour:

1. Using the v3 Single Zone Sample
2. Add a (jpeg) image to the /public folder
3. Update the root page.tsx to reference the image using the NextJS Image component
4. Test the image displays correctly in dev
5. Build the open-next distribution
6. Deploy with terragrunt
7. Open the CloudFront URL and view the root/home page.

## Expected behaviour

Expected: Expect the image to display
Actual: The image is not displayed

## Logs

No logs generated by image optimisation function.

Browser network trace returns a 403 error with the following body:
```
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>PHKAYV759GD08WKH</RequestId><HostId>BuLhAVTeQQ9Tpa3RUACkRSc5+9F1KfaQTuRNtAPdk7dyal2z+1UMEJxfLqmN5Qf5+vNtuFc4eMM=</HostId></Error>
```

**Comment by RJPearson94** [comment]
This has been released as part of v3.0.1 of the module
