### ISSUE TITLE
Archive creation error: expected a folder that open-next is not generated

### ISSUE THREAD

**Issue by DonsWayo** [RJPearson94/terraform-aws-open-next#38]
## Technical Details

- OS: MacOS
- Terraform Version: v1.5.7
- Provider Version OpenNext v3.1.3
- Module Version 3.0.3 (latest)
- Module Affected  tf-aws-open-next-zone
- Deployment Model Single zone

## Describe the bug

Hi

I get this error and I see in the open-next code that the folder is not generated. 

```bash
│ Error: Archive creation error
│ 
│   with module.open_next.data.archive_file.server_function[0],
│   on .terraform/modules/open_next/modules/tf-aws-open-next-zone/data.tf line 5, in data "archive_file" "server_function":
│    5: data "archive_file" "server_function" {
│ 
│ error creating archive: error archiving directory: could not archive missing directory: ../.open-next/server-function
╵
```

## Steps to Reproduce

Steps to reproduce the behaviour:

1. Next.js version : 14.2.7
2. Deploy

The open-next build

<img width="268" alt="Screenshot 2024-11-12 at 10 10 35" src="https://github.com/user-attachments/assets/5720f8ff-792d-42d0-b3b7-27f44c6ba844">

The open-next.config.ts

```ts
import type { OpenNextConfig } from 'open-next/types/open-next';
const config = {
  default: {
    override: {
      tagCache: 'dynamodb-lite',
      incrementalCache: 's3-lite',
      queue: 'sqs-lite',
    },
  },
} satisfies OpenNextConfig;
 
export default config;
```

So now I have generated 
.open-next/server-functions/default

and the tf module expects 
.open-next/server-function

Myabe I miss something?, thanks for the library!

## Expected behaviour

Deploy well without issues

**Comment by DonsWayo** [comment]
After define the   `open_next_version = "v3.1.7"` is working, maybe need to be mandatory?

**Comment by RJPearson94** [comment]
Ah ok. Thanks for the feedback @DonsWayo.
I have set the default to maintain backward compatibility and will look at whether that is still appropriate for the next major version. If you think the docs could be clear on this, then please let me know
