### ISSUE TITLE
Support for configuring layers in server function

### ISSUE THREAD

**Issue by tom-sanderson-bt** [RJPearson94/terraform-aws-open-next#39]
We have a requirement to configure a layer for monitoring in our deployment. From what I could see in the variables , there is no option for configuring a layer. Is this the case? 

## Describe the solution you'd like

Ability to configure a layer for our deployment 

```hcl
copy and paste an example terraform configuration here

  server_function = {
    additional_environment_variables = {
      ... my envs
    }
    
    layers = ["MY_LAYERS"]
  }
```

**Comment by RJPearson94** [comment]
Hi @tom-sanderson-bt,

Thanks for using the module.
Looking at the code, it appears layer support was missed. I am adding this now and will create a new version shortly.
