### ISSUE TITLE
Add support for OpenNext v2.2.x

### ISSUE THREAD

**Issue by abdullahdd** [RJPearson94/terraform-aws-open-next#4]
## Technical Details

- OS: Windows 11
- Terraform Version: 1.5.5
- Provider Version 4.67.0
- Module Version [e.g. v0.1.0]
- NextJS Version 13.5.3

## Describe the bug

I noticed that cache re-validation doesn't work in my application. I found two issues that might be due to misconfiguration.

1. Wrong environment variables are set for server-function. open-next expects REVALIDATION_QUEUE_REGION and REVALIDATION_QUEUE_URL while this package sets REINVALIDATION_QUEUE_REGION and REINVALIDATION_QUEUE_URL. This can be checked here https://github.com/sst/open-next/blob/24c5166377346bed1a029fb2223cf7f3b52a10d3/packages/open-next/src/adapters/plugins/routing/util.ts#L19
2. No dynamodb is setup as part of this terraform script which results in the exception attached below. I am not sure why this is happening, perhaps open-next has updated their code so that dynamodb is now necessary for cache invalidation to work. Please advice on this matter.

## Expected behaviour

We expect to see ISR/cache revalidation to work correctly.

## Logs

2023-10-18T07:32:36.297Z	33e9801e-003e-4c3b-84a9-0e6963eb46c3	ERROR	{
  clientName: 'DynamoDBClient',
  commandName: 'QueryCommand',
  input: {
    TableName: undefined,
    IndexName: 'revalidate',
    KeyConditionExpression: '#key = :key',
    ExpressionAttributeNames: { '#key': 'path' },
    ExpressionAttributeValues: { ':key': [Object] }
  },
  error: ValidationException: 1 validation error detected: Value null at 'tableName' failed to satisfy constraint: Member must not be null
      at pne (/var/task/cache.cjs:21:5519)
      at /var/task/cache.cjs:21:5744
      at ase (/var/task/cache.cjs:21:66529)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /var/task/cache.cjs:13:52849
      at async file:///var/task/index.mjs:13:4961
      at async file:///var/task/index.mjs:14:22859
      at async file:///var/task/index.mjs:2:35589
      at async Xh.getTagsByPath (/var/task/cache.cjs:44:201937)
      at async Xh.set (/var/task/cache.cjs:44:201509) {
    '$fault': 'client',
    '$metadata': {
      httpStatusCode: 400,
      requestId: 'A0MVCBAIFM2PRDKT5F8Q0O21NFVV4KQNSO5AEMVJF66Q9ASUAAJG',
      extendedRequestId: undefined,
      cfId: undefined,
      attempts: 1,
      totalRetryDelay: 0
    },
    __type: 'com.amazon.coral.validate#ValidationException'
  },
  metadata: {
    httpStatusCode: 400,
    requestId: 'A0MVCBAIFM2PRDKT5F8Q0O21NFVV4KQNSO5AEMVJF66Q9ASUAAJG',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}

**Comment by RJPearson94** [comment]
hi @abdullahdd,

Sorry, you have run into these issues. 

The first issue was a typo; this has been fixed and pushed out as part of v1.2.1.

Reading through the open next docs, DynamoDB was added as part of ISR. 
The recommended architecture diagram https://open-next.js.org/advanced/architecture#recommended-infrastructure-on-aws 
This change went out as part of v2.2.0 of open next. 
I will look at adding this to the module, in the meantime, if you can downgrade to v2.1.5 and use the updated module version then ISR should start working.

I will leave this issue open to add support for v2.2.0

Kind Regards
Rob

**Comment by abdullahdd** [comment]
Dear Rob,

Thank you so much for responding quickly and the amazing work that you have done with this module, we greatly appreciate that.

I guess we shouldn't have any issue downgrading to OpenNext 2.1.5. I will also get an update of the terraform module and update infrastructure and let you know if it works fine.

Regards,
Abdullah Atta

**Comment by jgeluk** [comment]
Using open-next 2.2.4 you end up with a zip file for the server-function lambda that's too large:

```
│ Error: creating Lambda Function (***): operation error Lambda: CreateFunction, https response error StatusCode: 413, RequestID: 1c062fbb-385d-45c7-a384-af7ffe9edc74, api error RequestEntityTooLargeException: Request must be smaller than 70167211 bytes for the CreateFunction operation
│ 
│   with module.open-next.module.server_function["root"].aws_lambda_function.lambda_function,
│   on ../modules/open-next/modules/tf-aws-lambda/main.tf line 3, in resource "aws_lambda_function" "lambda_function":
│    3: resource "aws_lambda_function" "lambda_function" {
```

It seems that the options are to either use layers or to use S3 to upload the zip file...

**Comment by abdullahdd** [comment]
> Using open-next 2.2.4 you end up with a zip file for the server-function lambda that's too large:
> 
> ```
> │ Error: creating Lambda Function (***): operation error Lambda: CreateFunction, https response error StatusCode: 413, RequestID: 1c062fbb-385d-45c7-a384-af7ffe9edc74, api error RequestEntityTooLargeException: Request must be smaller than 70167211 bytes for the CreateFunction operation
> │ 
> │   with module.open-next.module.server_function["root"].aws_lambda_function.lambda_function,
> │   on ../modules/open-next/modules/tf-aws-lambda/main.tf line 3, in resource "aws_lambda_function" "lambda_function":
> │    3: resource "aws_lambda_function" "lambda_function" {
> ```
> 
> It seems that the options are to either use layers or to use S3 to upload the zip file...

For me it was swc binaries which were getting into the zip file. To prevent that, I added following in my next.config.js

`experimental: {
        // Required:
        // appDir: true,
        //outputFileTracingRoot: path.join(__dirname, ''),
        outputFileTracingExcludes: {
            '*': [
                'node_modules/next/next-swc-fallback/@next/*',
                // 'node_modules/@swc/**/*',  
                'node_modules/@next/swc-win32-x64-msvc/*',
                'node_modules/@next/swc-linux-x64-musl/*',
                'node_modules/@next/swc-linux-x64-gnu/*',
                'node_modules/@next/swc-*/*',
                'node_modules/@esbuild/**/*',
                'node_modules/terser/**/*',
                'node_modules/webpack/**/*',
            ],
        },
    },`

**Comment by RJPearson94** [comment]
Hi @jgeluk, thanks for highlighting this, and thank you for the workaround @abdullahdd 

I want to make the module more flexible in future iterations to allow functions to be updated from S3, etc, along with other improvements around handling opennext versioning. Some of these changes may include breaking changes in the module, so I am thinking about the best way to move forward whilst minimising impact on users

**Comment by RJPearson94** [comment]
Hi @abdullahdd ,

Support for Open Next 2.2.x has been added and pushed to the Terraform Registry. Please upgrade to using at least v1.3.0 of the module to be able to utilise this functionality.

```tf
module "open-next" {
  source  = "RJPearson94/open-next/aws"
  version = "1.3.0"
}
```

I'm going to close the issue. Please feel free to open another issue for any additional feature requests/ issues.

Thanks for using the module

Kind Regards
Rob

**Comment by abdullahdd** [comment]
Thank you Rob for upgrading the module, will definately look into it.

Regards,
Abdullah Atta
