### ISSUE TITLE
Add "force_destroy" to "website_bucket"

### ISSUE THREAD

**Issue by jgeluk** [RJPearson94/terraform-aws-open-next#6]
Please add `force_destroy` to `website_bucket` so that doing a hard destroy of the whole infra works?

**Comment by RJPearson94** [comment]
Hi @jgeluk,

Apologies you ran into the issue, this has now been added to the module and released as part of v1.4.0.
Please update your terraform configuration to include the following

```tf
module "open-next" {
  source  = "RJPearson94/open-next/aws"
  version = "1.4.0"
}
```

Thanks for using the module

Kind Regards
Rob
