### ISSUE TITLE
Add timeouts to `aws_lambda_function` for lambda's deployed in VPCs

### ISSUE THREAD

**Issue by jgeluk** [RJPearson94/terraform-aws-open-next#7]
Please add timeouts to `resource "aws_lambda_function" "lambda_function"` since deploying lambdas in VPCs is often extremely slow. In our case our code accesses AWS Neptune endpoints so the `server-function` needs deployment in a VPC which often times out.

```
timeouts {
    create = "30m"
    update = "30m"
}
```
(Or make it configurable)

**Comment by RJPearson94** [comment]
Hi @jgeluk,

Apologies you ran into the issue, this has now been added to the module and released as part of v1.4.0.
Please update your terraform configuration to include the following

```tf
module "open-next" {
  source  = "RJPearson94/open-next/aws"
  version = "1.4.0"
}
```

Thanks for using the module

Kind Regards
Rob
